services:
  - type: web
    name: worksync-backend
    runtime: node
    plan: free
    rootDir: worksync/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: 26492
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://worksync-c.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://worksync-c.vercel.app,http://localhost:3000